bulbs = Ingredient.create(name:"Bulbs")
bulbs.children.create([{name:"Fennel"},{name:"Garlic"},{name:"Leeks"},{name:"Red Onions"},{name:"White Onions"},{name:"Shallots"},{name:"Spring onions"}])
flowers = Ingredient.create(name:"Flowers")
flowers.children.create([{name:"Broccoli"},{name:"Cauliflower"}])
leaves = Ingredient.create(name:"Leaves")
leaves.children.create([{name:"Brussel sprouts"},{name:"Cabbages"},{name:"Red Cabbages"},{name:"Savoy Cabbages"},{name:"Kale"},{name:"Lettuce"},{name:"Microgreens"},{name:"Salad greens"},{name:"Sliverbeet"},{name:"Spinach"},{name:"Watercress"},{name:"Witloof"},{name:"Bok Choi"}])
stems = Ingredient.create(name:"Stems")
stems.children.create([{name:"Asparagus"},{name:"Celery"},{name:"Kohlabi"},{name:"Rhuburb"}])
seeds = Ingredient.create(name:"Seeds")
seeds.children.create([{name:"Corns"},{name:"Bean sprouts"},{name:"Green beans"},{name:"Butter beans"}])
bean = Ingredient.create(name:"Bean")
bean.children.create([{name:"Soy bean"},{name:"Edamame"},{name:"Green pea"},{name:"Broad Bean"},{name:"Chickpea"},{name:"Green bean"},{name:"Kidney bean"},{name:"Sugarsnap"},{name:"Azuki bean"}])
mushroom = Ingredient.create(name:"Mushrooms")
mushroom.children.create([{name:"Shiitake mushrooms"},{name:"Shimeji mushrooms"},{name:"Eringi mushrooms"},{name:"Button mushrooms"},{name:"Portabellos"}])
roots = Ingredient.create(name:"Roots")
roots.children.create([{name:"Beetroots"},{name:"Carrots"},{name:"Celeriac"},{name:"Ginger"},{name:"Parsnips"},{name:"Radishes"},{name:"White Radishes"},{name:"Swedes"},{name:"Turnips"}])
tubers = Ingredient.create(name:"Tubers")
tubers.children.create([{name:"Potatoes"},{name:"Sweet potatoes"},{name:"Yums"},{name:"Taro"},{name:"Satoimo"}])
herbs = Ingredient.create(name:"Herbs")
herbs.children.create([{name:"Angelica"},{name:"Basil"},{name:"Thai Basil"},{name:"Bay"},{name:"Borage"},{name:"Chervil"},{name:"Chives"},{name:"Calendula Flowers"},{name:"Coriander"},{name:"Cornflowers"},{name:"Curly Kale"},{name:"Dill"},{name:"Lemon balm"},{name:"Lemongrass"},{name:"Lovage"},{name:"Marigold"},{name:"Majoram"},{name:"Mint"},{name:"Vietname Mint"},{name:"Nasturtium"},{name:"Oregano"},{name:"Parsley"},{name:"Pansy"},{name:"Rosemary"},{name:"Sage"},{name:"Salad burnet"},{name:"Savory"},{name:"Tarragon"},{name:"Thyme"},{name:"Verbena"},{name:"Wasabi"}])
fruits = Ingredient.create(name:"Fruits(non-sweet)")
fruits.children.create([{name:"Eggplant/Aubergine"},{name:"Cucumber"},{name:"Pumpkin"},{name:"Tomato"},{name:"Pepper"},{name:"Bell pepper"},{name:"Sweet Pepper"},{name:"Capsicum"}])
fruit = Ingredient.create(name:"Fruits")
fruit.children.create([{name:"Strawberry"},{name:"Blueberry"},{name:"Raspberry"},{name:"Kiwi"},{name:"Orange"},{name:"Lemon"},{name:"Yuzu"},{name:"Lime"},{name:"Mango"},
  {name:"Pineapple"},{name:"Apple"},{name:"Pear"},{name:"Papaya"},{name:"Lychee"}])
nuts = Ingredient.create(name:"Nuts")
nuts.children.create([{name:"Peanuts"},{name:"Almonds"},{name:"Cashewnuts"}])
noodle = Ingredient.create(name:"Noodle")
noodle.children.create([{name:"Udon"},{name:"Soba"},{name:"Ramen"}])
seasoning = Ingredient.create(name:"Seasoning")
seasoning.children.create([{name:"Salt"},{name:"Blackpepper"},{name:"Vegan Mayonaise"},{name:"Ketchup"},{name:"Mustard"},{name:"Paprika"},{name:"Chili Powder"},{name:"Sake"},{name:"Mirin"},{name:"Sugar"}])
oil = Ingredient.create(name:"Oil")
oil.children.create([{name:"Canola oil"},{name:"Olive oil"},{name:"Grapeseed oil"},{name:"Coconut oil"},
  {name:"Raspseed oil"}])