class Country < ActiveHash::Base
  self.data = [
      {id: 1, name: 'Afghanistan'}, {id: 2, name: 'Albania'}, {id: 3, name: 'Algeria'},
      {id: 4, name: 'Andorra'}, {id: 5, name: 'Angola'}, {id: 6, name: 'Antigua and Barbuda'},
      {id: 7, name: 'Argentina'}, {id: 8, name: 'Armenia'}, {id: 9, name: 'Australia'}, 
      {id: 10, name: 'Austria'}, {id: 11, name: 'Azerbaijan'}, {id: 12, name: 'Bahamas'}, 
      {id: 13, name: 'Bahrain'}, {id: 14, name: 'Bangladesh'}, {id: 15, name: 'Barbados'}, 
      {id: 16, name: 'Belarus'}, {id: 17, name: 'Belgium'}, {id: 18, name: 'Belize'}, 
      {id: 19, name: 'Benin'}, {id: 20, name: 'Bhutan'}, {id: 21, name: 'Bolivia (Plurinational State of)'}, 
      {id: 22, name: 'Bosnia and Herzegovina'}, {id: 23, name: 'Botswana'}, {id: 24, name: 'Brazil'}, 
      {id: 25, name: 'Brunei Darussalam'}, {id: 26, name: 'Bulgaria'}, {id: 27, name: 'Burkina Faso'}, 
      {id: 28, name: 'Burundi'}, {id: 29, name: 'Cabo Verde'}, {id: 30, name: 'Cambodia'}, 
      {id: 31, name: 'Cameroon'}, {id: 32, name: 'Canada'}, {id: 33, name: 'Central African Republic'}, 
      {id: 34, name: 'Chad'}, {id: 35, name: 'Chile'}, {id: 36, name: 'China'}, 
      {id: 37, name: 'Colombia'}, {id: 38, name: 'Comoros'}, {id: 39, name: 'Congo'}, 
      {id: 40, name: 'Cook Islands'}, {id: 41, name: 'Costa Rica'}, {id: 42, name: 'Croatia'}, 
      {id: 43, name: 'Cuba'}, {id: 44, name: 'Cyprus'}, {id: 45, name: 'Czechia'}, 
      {id: 46, name: 'Côte d\'Ivoire'}, {id: 47, name: 'Democratic Republic of the Congo'}, {id: 48, name: 'Denmark'}, 
      {id: 49, name: 'Djibouti'}, {id: 50, name: 'Dominica'}, {id: 51, name: 'Dominican Republic'},
      {id: 52, name: 'Ecuador'}, {id: 53, name: 'Egypt'}, {id: 54, name: 'El Salvador'},
      {id: 55, name: 'Equatorial Guinea'}, {id: 56, name: 'Eritrea'}, {id: 57, name: 'Estonia'}, 
      {id: 58, name: 'Eswatini'}, {id: 59, name: 'Ethiopia'}, {id: 60, name: 'Faroe Islands '}, 
      {id: 61, name: 'Fiji'}, {id: 62, name: 'Finland'}, {id: 63, name: 'France'}, 
      {id: 64, name: 'Gabon'}, {id: 65, name: 'Gambia'}, {id: 66, name: 'Georgia'}, 
      {id: 67, name: 'Germany'}, {id: 68, name: 'Ghana'}, {id: 69, name: 'Greece'}, 
      {id: 70, name: 'Grenada'}, {id: 71, name: 'Guatemala'}, {id: 72, name: 'Guinea'}, 
      {id: 73, name: 'Guinea-Bissau'}, {id: 74, name: 'Guyana'}, {id: 75, name: 'Haiti'}, 
      {id: 76, name: 'Honduras'}, {id: 77, name: 'Hungary'}, {id: 78, name: 'Iceland'}, 
      {id: 79, name: 'India'}, {id: 80, name: 'Indonesia'}, {id: 81, name: 'Iran (Islamic Republic of)'}, 
      {id: 82, name: 'Iraq'}, 
      {id: 83, name: 'Ireland'}, {id: 84, name: 'Israel'}, {id: 85, name: 'Italy'}, 
      {id: 86, name: 'Jamaica'}, {id: 87, name: 'Jordan'}, 
      {id: 88, name: 'Kazakhstan'}, {id: 89, name: 'Kenya'}, {id: 90, name: 'Kiribati'}, 
      {id: 91, name: 'Kuwait'}, {id: 92, name: 'Kyrgyzstan'}, {id: 93, name: 'Lao People\'s Democratic Republic'}, 
      {id: 94, name: 'Latvia'}, {id: 95, name: 'Lebanon'}, {id: 96, name: 'Lesotho'}, 
      {id: 97, name: 'Liberia'}, {id: 98, name: 'Libya'}, {id: 99, name: 'Lithuania'}, 
      {id: 100, name: 'Luxembourg'}, {id: 101, name: 'Madagascar'}, {id: 102, name: 'Malawi'}, 
      {id: 103, name: 'Malaysia'}, {id: 104, name: 'Maldives'}, {id: 105, name: 'Mali'}, 
      {id: 106, name: 'Malta'}, {id: 107, name: 'Marshall Islands'}, {id: 108, name: 'Mauritania'}, 
      {id: 109, name: 'Mauritius'}, {id: 110, name: 'Mexico'}, {id: 111, name: 'Micronesia (Federated States of)'}, 
      {id: 112, name: 'Monaco'}, {id: 113, name: 'Mongolia'}, {id: 114, name: 'Montenegro'}, 
      {id: 115, name: 'Morocco'}, {id: 116, name: 'Mozambique'}, {id: 117, name: 'Myanmar'}, 
      {id: 118, name: 'Namibia'}, {id: 119, name: 'Nauru'}, {id: 120, name: 'Nepal'}, 
      {id: 121, name: 'Netherlands'}, {id: 122, name: 'New Zealand'}, {id: 123, name: 'Nicaragua'},
      {id: 124, name: 'Niger'}, {id: 125, name: 'Nigeria'}, {id: 126, name: 'Niue'}, 
      {id: 127, name: 'North Korea'}, {id: 128, name: 'North Macedonia'}, {id: 129, name: 'Norway'}, 
      {id: 130, name: 'Oman'}, {id: 131, name: 'Pakistan'}, {id: 132, name: 'Palau'}, 
      {id: 133, name: 'Panama'}, {id: 134, name: 'Papua New Guinea'}, {id: 135, name: 'Paraguay'}, 
      {id: 136, name: 'Peru'}, {id: 137, name: 'Philippines'}, {id: 138, name: 'Poland'}, 
      {id: 139, name: 'Portugal'}, {id: 140, name: 'Qatar'}, {id: 141, name: 'Republic of Korea'}, 
      {id: 142, name: 'Republic of Moldova'}, {id: 143, name: 'Romania'}, {id: 144, name: 'Russian Federation'}, 
      {id: 145, name: 'Rwanda'}, {id: 146, name: 'Saint Kitts and Nevis'}, {id: 147, name: 'Saint Lucia'}, 
      {id: 148, name: 'Saint Vincent and the Grenadines'}, {id: 149, name: 'Samoa'}, {id: 150, name: 'San Marino'}, 
      {id: 151, name: 'Sao Tome and Principe'}, {id: 152, name: 'Saudi Arabia'}, {id: 153, name: 'Senegal'}, 
      {id: 154, name: 'Serbia'}, {id: 155, name: 'Seychelles'}, {id: 156, name: 'Sierra Leone'}, 
      {id: 157, name: 'Singapore'}, {id: 158, name: 'Slovakia'}, {id: 159, name: 'Slovenia'}, 
      {id: 160, name: 'Solomon Islands'}, {id: 161, name: 'Somalia'}, {id: 162, name: 'South Africa'}, 
      {id: 163, name: 'South Korea'}, {id: 164, name: 'South Sudan'}, {id: 165, name: 'Spain'}, 
      {id: 166, name: 'Sri Lanka'}, {id: 167, name: 'Sudan'}, {id: 168, name: 'Suriname'}, 
      {id: 169, name: 'Sweden'}, {id: 170, name: 'Switzerland'}, {id: 171, name: 'Syrian Arab Republic'}, 
      {id: 172, name: 'Tajikistan'}, {id: 173, name: 'Thailand'}, {id: 174, name: 'Timor-Leste'}, 
      {id: 175, name: 'Togo'}, {id: 176, name: 'Tokelau '}, {id: 177, name: 'Tonga'}, 
      {id: 178, name: 'Trinidad and Tobago'}, {id: 179, name: 'Tunisia'}, {id: 180, name: 'Turkey'},
      {id: 181, name: 'Turkmenistan'}, {id: 182, name: 'Tuvalu'}, {id: 183, name: 'Uganda'}, 
      {id: 184, name: 'Ukraine'}, {id: 185, name: 'United Arab Emirates'}, {id: 186, name: 'United Kingdom of Great Britain and Northern Ireland'}, 
      {id: 187, name: 'United Republic of Tanzania'}, {id: 188, name: 'United States of America'}, {id: 189, name: 'Uruguay'}, 
      {id: 190, name: 'Uzbekistan'}, {id: 191, name: 'Vanuatu'}, {id: 192, name: 'Venezuela (Bolivarian Republic of)'}, 
      {id: 193, name: 'Viet Nam'}, {id: 194, name: 'Yemen'}, {id: 195, name: 'Zambia'}, 
      {id: 196, name: 'Zimbabwe'}, {id: 197, name: 'Japan/日本'}
  ]
  end